### PR TITLE
feat: make analytics and logging stack optional

### LINKED ISSUE #97: feat: allow some services to be disabled by the end user as part of the installation
Most devs won't need these services:

influx
chronograf
mosquitto
source

and some like influx may be cpu/ram intensive.
Let's give an option for NOT installing and initializing those services, as part of the `placeos start` script.

### PR DESCRIPTION
**Pull request by caspiano**
Supersedes #49
Closes #97

### CODE REVIEW

**Comment by w-le** [comment]
Lgtm though any reason why we are downgrading elastic to 7.10.2 on line 41 of .env?
If not then I'll change that back to 7.16.2

**Comment by caspiano** [comment]
@w-le Problem was blacktop's logstash being a bit behind. 
If we can find an alpine based image that's up to date for logstash, I'll update it

**Comment by w-le** [comment]
Cool noted
All lgtm

**Review by w-le — APPROVED** [review]
Lgtm thanks!

**Review by w-le — APPROVED** [review]
Yep agree with these changes and the new default to disable analytics

**Pull request merged**
