### PR TITLE
feat(mqtt): add mosquitto container and config

### PR DESCRIPTION
**Pull request by w-le**
Adds a new docker container with Mosquitto MQTT broker including go-auth plugin.
Mounts a config file to it which specifies JWT auth in remote mode with the placeos `api` container doing the verification.

REQUIRES https://github.com/PlaceOS/nginx/pull/13 in order for client websocket requests to be proxied through to the mqtt broker.

- [x] https://github.com/PlaceOS/nginx/pull/13

### CODE REVIEW

**Comment by stakach** [comment]
@w-le this should be good to merge now, just need to resolve the conflicts

**Comment by w-le** [comment]
currently, `./placeos start` on an existing local deplolyment results in a stall.

stdout: hangs at `Bringing up services...`

logs get up to
```
placeos-1.2112.0: Pulling from placeos/init
Digest: sha256:1b1d8b6d357a46e6eafefbc3c516fcc482b951032e84108ee1720e5735d32c68
Status: Image is up to date for placeos/init:placeos-1.2112.0
docker.io/placeos/init:placeos-1.2112.0
already generated Chrongraf TOKEN_SECRET
already generated INFLUX_API_KEY, INFLUXDB_TOKEN
already generated PLACE_SERVER_SECRET, JWT_SECRET and JWT_PUBLIC
already generated kibana basic auth
already generated PLACE_INSTANCE_TELEMETRY_KEY
<manually aborted here after 15min wait)
```

**Comment by w-le** [comment]
since the last line to stdout is this https://github.com/PlaceOS/init/blob/master/scripts/generate-secrets#L117
I believe we are getting up to here, where running `placeos start`:
https://github.com/place-labs/partner-environment/blob/feat/mqtt-broker/placeos#L281

note that "Bringing up services..." does not get to stdout

**Comment by w-le** [comment]
Ok no idea why, but without any changes, when I ran `placeos start` for the third time, it completed fine.
Might have just been some strange local state in my docker wsl env. Let's ignore it unless someone else reports the same behaviour.

placeos starts up fine, chronograf logs are:
```
w-le@Mesh:~/code/placeos/partner-environment$ docker logs --tail 99 -f chronograf 
time="2021-12-23T05:12:21Z" level=error msg="failed to validate Oauth settings: missing Generic oauth setting[s]: client secret" basepath=invalid component=server
time="2021-12-23T05:12:27Z" level=info msg="Moving from version 1.8.0"
time="2021-12-23T05:12:27Z" level=info msg="Moving to version 1.9.1"
time="2021-12-23T05:12:27Z" level=info msg="Successfully created /var/lib/chronograf/backup/chronograf-v1.db.1.8.0"
time="2021-12-23T05:12:27Z" level=error msg="failed to validate Oauth settings: missing Generic oauth setting[s]: client secret" basepath=invalid component=server
time="2021-12-23T05:12:30Z" level=error msg="failed to validate Oauth settings: missing Generic oauth setting[s]: client secret" basepath=invalid component=server
time="2021-12-23T05:12:33Z" level=error msg="failed to validate Oauth settings: missing Generic oauth setting[s]: client secret" basepath=invalid component=server
```

**Review by stakach — APPROVED** [review]
LGTM

**Comment by w-le** [comment]
not yet, still fixing

**Pull request merged**
